appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Jak/pnqGIdBQJ0Vm4iAFhbMblqRN2vAQQsjHoixPqqWE8fEhPutb2f9MBvFGtTYVgMg7VvfmSdOLq5Fy18KcTlOZCYs9VTvkN/MhTGOTUQ3I3Ispjw2ssdq/yYo7Mi1OBixoJdjWHxTAeb1ukAZTpjyJ/WDHuJe6Pxdo5eqfiHxCBhHy6K+TlAyR8QhhEgaDlR5qrAMTU7PqJmNNBK7xPV+JJa/1fdBxMp/ySxOPwrkiuYnXz5cNXoYaFm6RPaRh580i2DPzWIs23jIXsPxhC3kkQIdjKIY7fkGT4OoYaHzzw72LYRnnb6FThiFIJlcK9j66hTlM5UIYfakhhFb7LoutdN/RBLRi/WLujN8HP9BY2A6pa8tvm8R5vUyDoYKJ6mAAWT6PBpVBzN7vQ2wg549rIn/pIRrft26O9oEC5xkG5MuszdWmk6SzE5XhtCWhE3nHxe/clHLRzZwnbHKMsp08pMwmdOZIE4yBcsRiEBfBvY2xb8et05gg0udyCAMM/JbttGmOdpsyjFuhGih0F0VfoK8BiEfYJOkkak/b7+toQHNv1qRAWlWz886OC9AsPS+NyRgE7ozRyk8R8u+H7e84MnqwDC8quyYguOrfrFxDVM8U5VESDmDBYUfmPj0MI1e75x9er5xC4cfYmryLlvOk8Xks8p5kE6RtNrufJwI=}
